### ISSUE TITLE
Bot has difficulty handling steep price increases

### ISSUE THREAD

**Issue by theD1360** [theD1360/BTC-php-tradebot#1]
If prices increase or decrease too steeply they will fall out of the bots trading range. The only way I know of fixing this is to come up with a short sell algorithm. Short selling is dangerous and can lead to losing large amounts of money if not done correctly.

**Comment by domtancredi** [comment]
Do you have the logic for the algorithm you want? Or is this an issue with defining logic to handle it?

**Comment by theD1360** [comment]
This is an older issue. I haven't tested the latest code enough to verify if this issue has been resolved yet.
