### ISSUE TITLE
Daemon not yet started ...

### ISSUE THREAD

**Issue by orbb70** [theD1360/BTC-php-tradebot#3]
Notice: Use of undefined constant SIGHUP - assumed 'SIGHUP' in /usr/local/php5/lib/php/System/Daemon.php on line 1660
... etc
and ..
Notice: Use of undefined constant SIG_IGN - assumed 'SIG_IGN' in /usr/local/php5/lib/php/System/Daemon.php on line 1660
[May 07 16:12:45] info: Daemon not yet started so this will be written on-screen [May 07 16:12:45] notice: unable to forge startup script for non existing daemon_filepath: @dirname()/@basename(), try setting a valid appDir or appExecutable [May 07 16:12:45] notice: unable to forge startup script. daemon_filepath: @dirname()/@basename(), needs to be executable first [May 07 16:12:45] warning: Unable to create startup file [l:1185] [May 07 16:12:45] notice: unable to write init.d script
Fatal error: Uncaught <table style="border: 1px" cellspacing="0"> <tr><td colspan="3" style="background: #ff9999"> <b>System_Daemon_Exception</b>: PHP is compiled without --enable-pcntl directive in <b>/var/www/html/test_bot/daemon.php</b> on line <b>45</b></td></tr> <tr><td colspan="3" style="background-color: #aaaaaa; text-align: center; font-weight: bold;">Exception trace</td></tr> <tr><td style="text-align: center; background: #cccccc; width:20px; font-weight: bold;">#</td><td style="text-align: center; background: #cccccc; font-weight: bold;">Function</td><td style="text-align: center; background: #cccccc; font-weight: bold;">Location</td></tr> <tr><td style="text-align: center;">0</td><td>System_Daemon::start()</td><td>/var/www/html/test_bot/daemon.php:45</td></tr> <tr><td style="text-align: center;">1</td><td>{main}</td><td>&nbsp;</td></tr> </table> thrown in /usr/local/php5/lib/php/System/Daemon.php on line 551

**Comment by orbb70** [comment]
i have a php 5.2 not CLI

**Comment by orbb70** [comment]
sory , i succesfuli install and run bot ))))))))))) thank you !!!
use PHP 5.3 CLI

**Comment by theD1360** [comment]
Glad to you were able to get it running
